### ISSUE TITLE
How to use PersistGate from redux-persist with UI Kitten

### ISSUE THREAD

**Issue by thivyakm** [akveo/react-native-ui-kitten#1534] opened 2021-10-13 16:16 UTC
I'm using redux Provider and PersistGate like below code
`<>`
  `  <IconRegistry icons={FeatherIconsPack} />`
  `  <ApplicationProvider {...eva} theme={{...eva.light, ...theme}}>`
  `    <Provider store={store}>`
  `      <PersistGate persistor={persistor}>`
  `        <NavigationContainer>`
  `          <RootNavigator />`
  `        </NavigationContainer>`
  `      </PersistGate>`
  `    </Provider>`
  `  </ApplicationProvider>`
  `</>`
 And also UI tried like this
`<>`
  `  <Provider store={store}>`
  `    <PersistGate persistor={persistor}>`
  `      <IconRegistry icons={FeatherIconsPack} />`
  `      <ApplicationProvider {...eva} theme={{...eva.light, ...theme}}>`
  `        <NavigationContainer>`
  `          <RootNavigator />`
  `        </NavigationContainer>`
  `      </ApplicationProvider>`
  `    </PersistGate>`
  `  </Provider>`
  `</>`
    
  There is no error. But my screen display is blank.
  If I removed the <ApplicationProvider> tag it is working fine or I remove the <PersistGate> tag it is working fine
  How can I use PersistGate with UI Kitten

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   "^2.1.1"     |
| @ui-kitten/components   |     "^5.1.1"    |
``

**Comment by malashkevich** [comment] 2021-11-01 14:14
duplicate of #1533

**Closed by malashkevich** 2021-11-01 14:14 UTC

**Comment by manhninh** [comment] 2022-01-21 12:57
> duplicate of #1533

I have configured like you but it doesn't work.

import * as eva from '@eva-design/eva';
import {ApplicationProvider, IconRegistry} from '@ui-kitten/components';
import {EvaIconsPack} from '@ui-kitten/eva-icons';
import React from 'react';
import {Text, View} from 'react-native';
import {Provider} from 'react-redux';
import {PersistGate} from 'redux-persist/integration/react';
import RootComponent from './src';
import {persistor, store} from './src/store/configureStore';

const onBeforeLift = () => {
  console.log('asdasd a as a s');
};

const App = () => {
  console.log('asdasd');
  return (
    <>
      <IconRegistry icons={EvaIconsPack} />
      <ApplicationProvider {...eva} theme={eva.light}>
        <Provider store={store}>
          <PersistGate
            loading={
              <View>
                <Text>Loading</Text>
              </View>
            }
            onBeforeLift={onBeforeLift}
            persistor={persistor}>
            <RootComponent />
          </PersistGate>
        </Provider>
      </ApplicationProvider>
    </>
  );
};

export default App;
