### ISSUE TITLE
[DatePicker] Unable to select a different Month from a different Year than the current

### ISSUE THREAD

**Issue by montanhes** [akveo/react-native-ui-kitten#1691] opened 2022-12-09 20:08 UTC
## To Reproduce

I have a screen with a DatePicker that breaks every time I try to select a different month from another year.

```js
import React, { useState} from 'react';
import subYears from 'date-fns/subYears';
import addYears from 'date-fns/addYears';
import { Datepicker } from '@ui-kitten/components';

const dateComp = () => {
  const [expense, setExpense] = useState({
    date: new Date(),
    value: '',
    info: '',
  });

  return (
    <>
      <Datepicker
        date={expense.date}
        max={new Date(addYears(new Date(), 30))}
        min={new Date(subYears(new Date(), 10))}
        label='Date'
        onSelect={nextDate => setExpense({...expense, date: nextDate})}
      />
    </>
  )
}

export default dateComp
```

On the first picturew you will able to check that my current date is 09/12/2022 (brazilian dd/mm/yyyy date format) then I click on the 2022-2033 area and it's display the years that I'm able to select, so I select a different year.

On the second picture I should be able to select the month, but no matter the month I click on it I get the error on the last picture.

First Picture
![image](https://user-images.githubusercontent.com/983688/206785306-4c1cf202-5cab-404c-9c25-d45fc46c9625.png)

Second Picture
![image](https://user-images.githubusercontent.com/983688/206785384-37955785-150f-4426-99c9-c8d6528d4ac0.png)

Last Picture
![image](https://user-images.githubusercontent.com/983688/206785411-ed470b9f-9b7d-4f11-b06b-43b48db0e3c4.png)

## Expected behavior

I expect to be able to select a day from the selected month/year.

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |  ^2.1.1      |
| @ui-kitten/components   |  ^5.1.2       |

## Environment information

```bash

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
  Binaries:
    Node: 14.21.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  npmPackages:
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 

```

**Comment by greenfrvr** [comment] 2022-12-12 19:09
@ramonMontanhes I was not able to reproduce the issue with the snippet you provided. I've checked on both platforms and it is working fine. what makes you think that it's `DatePicker` crash? could you share some more details, how to reproduce the issue?

**Comment by ramonMontanhes** [comment] 2022-12-12 19:19
Hi @greenfrvr, another user has the same issue as me, but he is using EXPO,

https://github.com/akveo/react-native-ui-kitten/issues/1687

Using my example if you click on the displayed items on image below (1 first, 2 after) it does not causes the reported error?

![image](https://user-images.githubusercontent.com/983688/207134097-26630b94-3c06-44f5-959f-346b87cb6e9c.png)

I could provide more information if you want, I can even try to create this simple project and add it to github.

currently I'm using the below dependencies on my project:

```json
"dependencies": {
    "@eva-design/eva": "^2.1.1",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "@react-navigation/stack": "^6.3.1",
    "@ui-kitten/components": "^5.1.2",
    "@ui-kitten/date-fns": "^5.1.2",
    "@ui-kitten/eva-icons": "^5.1.2",
    "axios": "^0.27.2",
    "date-fns": "^2.29.3",
    "dinero.js": "^1.9.1",
    "lodash": "^4.17.21",
    "react": "18.1.0",
    "react-native": "0.70.4",
    "react-native-ble-manager": "^8.4.4",
    "react-native-blob-util": "^0.16.4",
    "react-native-gesture-handler": "^2.6.1",
    "react-native-html-to-pdf": "^0.12.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-ping": "^1.2.7",
    "react-native-quick-md5": "^3.0.4",
    "react-native-reanimated": "^2.12.0",
    "react-native-safe-area-context": "^4.3.3",
    "react-native-screens": "^3.17.0",
    "react-native-share": "^8.0.0",
    "react-native-svg": "^13.2.0",
    "react-native-thermal-receipt-printer-image-qr": "^0.1.10",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^11.23.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-test-renderer": "18.1.0"
  },
```

I'm running my app on my smartphone that runs Android 10 (Xiaomi Mi A2). I don't use EXPO.

But I can provide more details, just let me know what you need.

**Comment by chrismathews2007** [comment] 2022-12-13 11:15
> 

@greenfrvr I got the same issue, I'm using expo. 

please check my repo [https://github.com/chrismathews2007/UIKittenDatePicker](url)

Thank you @ramonMontanhes  for mentioning my issue.

**Comment by ricardodolnl** [comment] 2023-01-05 15:00
I fixed my problem by adding a `min={}` date of previous year.

**Comment by TakaoNarikawa** [comment] 2023-01-18 10:05
I got the same issue. I fixed by downgrading `@ui-kitten/components` to `5.1.1`

**Comment by bataevvlad** [comment] 2023-05-15 10:21
Related issue.

https://github.com/akveo/react-native-ui-kitten/issues/1706

To use the DataPicker correctly, you should specify the min and max values

**Closed by bataevvlad** 2023-05-15 10:21 UTC
