### ISSUE TITLE
Display Scrollable Grid view in RkTabView component

### ISSUE THREAD

**Issue by userrails** [akveo/react-native-ui-kitten#66] opened 2017-12-15 04:33 UTC
**Please find the source code in snack.expo.io**
https://snack.expo.io/@przbadu/navigationtest

Expected:

`RkTabView`

[![RkTabView](https://i.stack.imgur.com/zACk7.png)](https://i.stack.imgur.com/zACk7.png)

and ScrollView with flex grid

[![flex grid](https://i.stack.imgur.com/p7l5w.png)](https://i.stack.imgur.com/p7l5w.png)

should work. Please let me know what I am missing here.

> I have also added some description in: https://stackoverflow.com/questions/47825742/make-scrollview-work-with-rktabview

**Comment by sergey-kozel** [comment] 2017-12-28 09:56
Hi, @userrails,

Indeed, there is a problem in our framework v2.0.1

The content of RkTabView is wrapped into `<View>` and it doesn't contain any styles. And you got the following structure:
```
<View>
  <ScrollView>
    ...your content
  </ScrollView>
</View>
```
The problem is `ScrollView` required bounded height. But it doesn't have. This was already fixed in dev branch and we are going to make a release soon. There this internal `View` will have `flex:1` by default and will be available for styling through `contentContainer` component.

Unfortunately, right now there are no easy ways to resolve this issue. You can wrap your `ScrollView` into other `View` with fixed height. Or you can fix that problem `View` in sources of RkTabView:
```
337: <View style={{flex:1}}>
338:   {tabs[this.state.index]}
339: </View>
```
But of course, I don't know how you use the framework and which option will be acceptable for you.

Sorry for the inconvenience!

**Closed by sergey-kozel** 2017-12-28 09:56 UTC
