### ISSUE TITLE
Overwrite default border radius

### ISSUE THREAD

**Issue by DarWiM** [akveo/react-native-ui-kitten#1305] opened 2020-12-10 21:45 UTC
## 💬 Question
Hello. Please tell me how to set the default border radius for all elements?
Tried this and it works on web, but doesn't work on android:
```js
const customMapping = {
  strict: {
    'border-radius': 0,
  },
  components: {
  },
};
```
Here's the error:
```
Error while updating property 'borderRadius' of a view managed by: RCTView

java.lang.String cannot be cast to java.lang.Double

- - - - - -

updateViewProp
ViewManagersPropertyCache.java:13

setProperty
ViewManagerPropertyUpdater.java:2

updateProps
ViewManagerPropertyUpdater.java:9

updateProperties
ViewManager.java:3

createView
NativeViewHierarchyManager.java:8

...

```

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.0.0    |
| @ui-kitten/components   |    5.0.0     |

**Comment by artyorsh** [comment] 2020-12-11 07:05
Yes, I've tried that too a few days ago. You can use something like 0.01 as a workaround 😅

**Comment by AntonBorovoi** [comment] 2021-07-05 11:50
Seems like the issue was caused by wrong Eva processing for strict mapping rules.
`'border-radius': 0` maps into `borderRadius: 'border-radius'` style instead of `borderRadius: 0`

Should be fixed by https://github.com/eva-design/eva/pull/87

**Closed** 2021-07-29 10:34 UTC
