### ISSUE TITLE
Error when using custom mapping on Typescript

### ISSUE THREAD

**Issue by rayhk6** [akveo/react-native-ui-kitten#1617] opened 2022-04-25 09:04 UTC
## To Reproduce

using custom mapping 

## Expected behavior
no error message

## Link to runnable example or repository (highly encouraged)
<img width="613" alt="Screenshot 2022-04-25 at 5 01 59 PM" src="https://user-images.githubusercontent.com/13505570/165056922-39059c84-5656-41dd-abe7-8b9de266d73a.png">

`{
  "components": {
    "Input": {
      "meta": {},
      "appearances": {
        "default": {
          "variantGroups": {
            "status": {
              "basic": {
                "labelColor": "text-basic-color",
                "borderColor": "background-color",
                "backgroundColor": "input-background-color",
                "state": {
                  "focused": {
                    "borderColor": "background-color",
                    "backgroundColor": "input-focused-background-color"
                  },
                  "disabled": {
                    "backgroundColor": "input-background-color"
                  }
                }
              }
            }
          }
        }
      }
    },
}
}`

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    2.1.1    |
| @ui-kitten/components   |    5.1.2     |

## Environment information

```bash

```

**Comment by nafplann** [comment] 2022-05-20 13:14
try this 
`customMapping={{ ...eva.mapping, ...customMapping }}>`

**Comment by greenfrvr** [comment] 2022-10-28 11:11
@rayhk6 hey! from your custom mappings snippet it seems that the problem is in your mappings. as I can see `meta` field is empty, which is required to describe parameters which may be configured for current component. please check `CustomSchemaType` type it describes interface expected as custom mappings. also you can check eva default mappings as a reference. perhaps there is inconsistency with documentation, but from source code side it seems all `meta` fields a required (even in case of overriding existing components).

**Comment by greenfrvr** [comment] 2022-10-28 11:19
@rayhk6 I have checked applying custom mappings with the snippet you had provided and I can confirm that describing mappings properly (e.i. according to declared interface) makes ts validation being correct. we'll check if our docs are outdated for custom mappings, but for now I'll close this ticket.

**Closed by greenfrvr** 2022-10-28 11:19 UTC
