### ISSUE TITLE
Input long placeholder bug

### ISSUE THREAD

**Issue by garrylachman** [akveo/react-native-ui-kitten#1415] opened 2021-04-26 03:15 UTC
## 🐛 Bug Report
In some cases, when the placeholder is longer than input the text is cutted to 1.5 lines.
The bug can be Reproduce on Android only.

## To Reproduce
https://snack.expo.io/9f7pW21Ff

Run in Android device and click on toggle theme.

First render
![](https://i.imgur.com/JbrKR0w.png)

Click on change theme
![](https://i.imgur.com/NGyv8RC.png)

Click on change theme again
![](https://i.imgur.com/9Lmfr0c.png)

Write text (working as expected)
![](https://i.imgur.com/PyuD6Ho.png)

Delete text - same issue
![](https://i.imgur.com/oBiLbWF.png)

## Expected behavior
A single line

**Comment by whitestranger7** [comment] 2021-06-30 18:03
Hey, @garrylachman. Thanks for noticing. This particular bug relate to react-native issue right [there](https://github.com/facebook/react-native/issues/30666). The issue is appearing while changing input color value from eva config. We're not planning to refuse from getting color from eva config, so we hope that react-native bug will be fixed shortly. If not - we're going to fix it with closest release

**Closed by whitestranger7** 2021-06-30 18:03 UTC

**Comment by CodeQiangZi** [comment] 2021-12-09 13:26
还是有问题啊
