### ISSUE TITLE
Icon in caption not work

### ISSUE THREAD

**Issue by allenalston** [akveo/react-native-ui-kitten#1625] opened 2022-06-16 07:18 UTC
When I use Input caption api, I want to use icon in the renderCaption, but not shown.

This is my code:

``` javascript
 const AlertIcon = style => <Icon {...style} name="alert-circle-outline" />;
 const renderCaption = msg => {
    return (
      <View style={styles.captionContainer}>
        {AlertIcon(styles.captionIcon)}
        <Text status="danger" category="c1">
          {msg}
        </Text>
      </View>
    );
  };
```

``` jsx
 <Input
    placeholder="Username"
     accessoryRight={props => <Icon {...props} name="person" />}
     onBlur={onBlur}
     onChangeText={onChange}
     value={value}
     caption={errors.username && (() => renderCaption('Required'))}
 />
```

<img width="375" alt="image" src="https://user-images.githubusercontent.com/18042277/174016090-6b279f91-b184-42c2-957c-a01d72043876.png">

This is the result:

![image](https://user-images.githubusercontent.com/18042277/174014391-18776c02-9ee9-4301-97af-b9ff7e238963.png)

**Comment by Valar103769** [comment] 2022-08-29 12:49
maybe this project had dead

**Comment by greenfrvr** [comment] 2022-10-28 08:39
@allenalston sorry for late response. could you please share `captionContainer` and `captionIcon` styles?

**Comment by greenfrvr** [comment] 2022-10-28 09:03
@allenalston actually I missed one thing. the issue is how you are passing styles to `Icon`. currently you are destructuring style object and pass each attribute as a separate prop. your icon component should like this instead:
`const AlertIcon = style => <Icon style={style} name="alert-circle-outline" />;`

I'm closing the issue, as I checked this on a test project and caption functionality is working as expected.

**Closed by greenfrvr** 2022-10-28 09:03 UTC
