### ISSUE TITLE
Invalid value for prop `dispatch` on <div> tag

### ISSUE THREAD

**Issue by VladimirHumeniuk** [akveo/react-native-ui-kitten#884] opened 2020-02-12 04:03 UTC
Getting this errors in v.4.4.0 in web app. 
![image](https://user-images.githubusercontent.com/20288162/74301898-ddae4a00-4d54-11ea-85d8-b67349e5e2a7.png)

**Comment by artyorsh** [comment] 2020-02-12 15:18
It's a known issue, [see my reply](https://github.com/akveo/react-native-ui-kitten/pull/812#issuecomment-573528298) on this

**Comment by lesmo** [comment] 2020-02-22 03:18
> It's a known issue, [see my reply](https://github.com/akveo/react-native-ui-kitten/pull/812#issuecomment-573528298) on this

... plus a duplicate of #669 🤔

AFAIK this **warning** doesn't really affect the final product, when building for release it works properly. It's just a bit annoying. We've successfully used `ui-kitten` in production for an App that was cross platform (Web, Android, iOS), although we quickly deprecated it's development because of business reasons... so be not afraid, I think? 😅

**Comment by artyorsh** [comment] 2020-02-24 08:07
Will be fixed in 5.0 :)

**Closed** 2020-04-08 15:06 UTC
Labels: :globe_with_meridians: Web, :iphone: Components

**Comment by emiljano17** [comment] 2022-04-07 15:44
how did you deal with this error?
