### ISSUE TITLE
[Typescript] onPress does not exist on MenuItem (v5)

### ISSUE THREAD

**Issue by kaminskypavel** [akveo/react-native-ui-kitten#1024] opened 2020-04-14 18:56 UTC
## 🐛 Bug Report

while the docs for 5.0.0-alpha.1 implies that onPress should be used with MenuItem
```    <React.Fragment>
      <Text category='h6'>{selectedTitle}</Text>
      <Menu>
        <MenuItem title='Users' onPress={onUsersPress}/>
        <MenuItem title='Orders' onPress={onOrdersPress}/>
        <MenuItem title='Transactions' onPress={onTransactionsPress}/>
        <MenuItem title='Settings' onPress={onSettingsPress}/>
      </Menu>
    </React.Fragment>
```
typescript implies onPress is not defined

> Error:(69, 9) TS2322: Type '{ accessoryLeft: (style: any) => Element; title: string; onPress: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<StyledComponentProps & MenuItemProps, any, any>> & Readonly<...> & Readonly<...>'.
>   Property 'onPress' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<StyledComponentProps & MenuItemProps, any, any>> & Readonly<...> & Readonly<...>'.
> 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     ^5.0.0-alpha.1   |
| @ui-kitten/components   |   ^5.0.0-alpha.1      |
| typescript |   ^3.8.3      |

## Environment information

```bash

```

**Comment by artyorsh** [comment] 2020-04-17 22:45
Thanks for reporting 👍 
This is caused by same issue as for #1030. Will be resolved in alpha.2

**Closed by artyorsh** 2020-04-17 22:45 UTC

**Comment by kaminskypavel** [comment] 2020-05-04 15:41
@artyorsh any idea when alpha2 will be released? is there anywhere we can planned milestones?
Thanks!

**Comment by artyorsh** [comment] 2020-05-04 23:22
@kaminskypavel
I guess I’m able to do it this week with publishing stable ;) You can track the upcoming changelog in related PR. Thanks for your interest

**Comment by kaminskypavel** [comment] 2020-05-05 11:10
Amazing! Thanks!
