### ISSUE TITLE
Demo Dashboard gives red screen

### ISSUE THREAD

**Issue by tmaly1980** [akveo/react-native-ui-kitten#18] opened 2017-06-30 12:36 UTC
I've downloaded the demo app. Every other screen works fine, but the dashboard gives a red screen. This is a fresh clone from github and I've run "yarn install" then "react-native run-ios"

Is there something I can fix quickly on my end? I'm really liking this UI toolkit.

![screen shot 2017-06-30 at 5 35 07 am](https://user-images.githubusercontent.com/7697371/27735743-fc7653ac-5d55-11e7-8c29-80ae5c0c38e5.png)

**Comment by tmaly1980** [comment] 2017-06-30 12:39
Not sure if this should be in the kittenTracks repo or here. I've created an issue in both.

**Comment by SashaSkywalker** [comment] 2017-06-30 14:24
closed as duplicate of https://github.com/akveo/kittenTricks/issues/7

**Closed by SashaSkywalker** 2017-06-30 14:24 UTC

**Comment by michaelspeed** [comment] 2017-07-29 07:24
this is still no if i use RkText
like this
<RkText rkType='header2 inverseColor'>{this.props.post.user.name} {this.renderLinkedPeople()}</RkText>
