### ISSUE TITLE
require cycle in styles/themeManager.js and styles/styleSheet.js

### ISSUE THREAD

**Issue by Gitldx** [akveo/react-native-ui-kitten#181] opened 2018-11-22 09:46 UTC
they reference each other
is it possible to avoid the warning?

**Comment by artyorsh** [comment] 2018-11-22 11:56
Hi @Gitldx 

Please describe your environment to help us resolve this

**Comment by Gitldx** [comment] 2018-11-22 15:45
> Hi @Gitldx
> 
> Please describe your environment to help us resolve this

thank you so much,artyorsh ,here is the dependecies

"dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-ui-kitten": "^3.1.2"
  }

**Comment by artyorsh** [comment] 2018-11-22 19:40
@Gitldx 
It seems to be [bundler issue](https://github.com/facebook/react-native/issues/20841). 
Anyway, I could not reproduce this in [clean project](https://github.com/artyorsh/react-native-clean)

**Comment by Gitldx** [comment] 2018-11-23 08:35
> @Gitldx
> It seems to be [bundler issue](https://github.com/facebook/react-native/issues/20841).
> Anyway, I could not reproduce this in [clean project](https://github.com/artyorsh/react-native-clean)

thank you to your quick reply
yes, my problem is the same as the one you copy to me: [bundler issue](https://github.com/facebook/react-native/issues/20841#issuecomment-422360627)
and I can not reproduce the warning according to your code :clean project.

Anyway,I think it's better to extract the shared code from styles/themeManager.js and styles/styleSheet.js to a new file.Although the warning seems harmless by now

**Comment by hatemalimam** [comment] 2018-12-25 16:40
I'm having the same warnings.
I've managed to ignore them for now by adding this to the app entry point:

`YellowBox.ignoreWarnings(['Require cycle:']);`

Related: https://github.com/facebook/metro/issues/287

**Comment by artyorsh** [comment] 2018-12-26 09:38
@hatemalimam @Gitldx 
that's not the way it should be fixed
we're currently working on major update, so feel free to open pr's
thanks!

**Comment by artyorsh** [comment] 2019-06-11 14:17
This stays actual for v3.*
Check out the brand new v4 update!

**Closed by artyorsh** 2019-06-11 14:17 UTC
Labels: bug
