### ISSUE TITLE
Button content does not render text correctly

### ISSUE THREAD

**Issue by nmokkenstorm** [akveo/react-native-ui-kitten#603] opened 2019-09-06 10:14 UTC
### Issue type

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

I just installed the library in an existing Expo App, and in the process of replacing the default react-native components with their equivalents in UI Kitten. After moving the content from the title prop to inside the component, the text renders incorrectly, always dropping the last word, unless I add a trailing space.

**Expected behavior:**

The button should just straight up render the content as is

**Steps to reproduce:**

Create a component using the default react native button, and set the title to 'FOO BAR', it will render 'FOO BAR' as content. If you then replace the button component with the one from UI Kitten, it will render just 'FOO'. Using `{'FOO BAR '}`, with an extra space, will render 'FOO BAR'

**Related code:**

```
import React from 'react'
import { withNavigation } from 'react-navigation'
import { Button } from 'react-native-ui-kitten';

export default withNavigation(
    ({navigation}) =>
        <Button onPress={ _ => navigation.navigate('ItemCreate') } size='small' appearance='ghost'>
            ADD AN ITEM
        </Button>
)
```

### Other information:

**OS, device, package version**
```
OS: macOS Mojave, 10.14.5
Packages: React Native 33.0.0., Expo 33.0.0, UI Kitten 4.1.1
```

**Comment by nmokkenstorm** [comment] 2019-09-06 10:24
To add to this, if the content is only one word (Like Register), the button renders regis-. Again, the trick with setting the inner content as `{'Register '}` works, but this feels very convoluted.

**Comment by artyorsh** [comment] 2019-09-06 18:44
@nmokkenstorm Unable to reproduce. See it in action on a [Snack](https://snack.expo.io/@art.yorsh/ui-kitten---welcome)
Do you use any additional stylings or custom fonts?

**Comment by nmokkenstorm** [comment] 2019-09-09 11:57
@artyorsh I'm using the mapping and light theme from eva-design in the application provider in the root node, no other custom styling. Worth noting might be that the navigation structure from the default React Native / Expo setup is still in, which might (?) influence styling or fonts.

**Comment by artyorsh** [comment] 2019-09-09 15:37
@nmokkenstorm
No, definitely. Could you please share some screenshots?

**Comment by nmokkenstorm** [comment] 2019-09-09 15:47
![WhatsApp Image 2019-09-09 at 17 41 01](https://user-images.githubusercontent.com/33529698/64545548-3c484580-d329-11e9-8e4d-b1e3ad275576.jpeg)
![WhatsApp Image 2019-09-09 at 17 41 01(1)](https://user-images.githubusercontent.com/33529698/64545549-3ce0dc00-d329-11e9-941e-f2e680b00fcb.jpeg)

```
<Button onPress={submitLogin} disabled={ loading }>
    {'Login '}
</Button>

<Button onPress={submitLogin} disabled={ loading }>
    Login
</Button>
```

Attached screenshots are from a physical One Plus 6T running Android 9, if it matters at all.

I have quite a bit of experience with React, but I inherited this particular React Native project and I'm not well versed in the ways of mobile / native at all, so it could be that I'm missing something obvious here.

**Comment by artyorsh** [comment] 2019-10-30 11:51
@nmokkenstorm I'm sorry for the late reply. Was it resolved? If no, can you inspect the fonts you're using?

**Comment by flexbox** [comment] 2019-11-19 09:07
Hello @nmokkenstorm 
I know it's a frustrating but it's not related with kitten UI.

As @artyorsh says this issue is due to a bug in the font on OnePlus phones

You can found some info here:
- Official thread on React Native : https://github.com/facebook/react-native/issues/15114
- Expo forums : https://forums.expo.io/t/text-cut-off-on-oneplus-device/4999/4

And feel free to close this issue if you problem is solved 😉

**Comment by artyorsh** [comment] 2019-11-19 10:56
Thanks for the detailed explanation @flexbox 👍 
[Here is one more notice](https://github.com/akveo/react-native-ui-kitten/issues/582#issuecomment-547933196) on having issues with fonts on Apple devides. Will just leave it here for easier navigation

**Closed by artyorsh** 2019-11-19 10:56 UTC
Labels: help wanted, module:ui, needs info
